version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  fluentd:
    image: fluent/fluentd
    ports:
      - "24224:24224"
  fdns-ms-object:
    image: cdcgov/fdns-ms-object
    ports:
      - "8083:8083"
    environment:
      OBJECT_PORT: 8083
  fdns-ms-combiner:
    image: cdcgov/fdns-ms-combiner
    ports:
      - "8085:8085"
    environment:
      COMBINER_PORT: 8085
  fdns-ms-hl7-utils:
    image: cdcgov/fdns-ms-hl7-utils
    ports:
      - "8080:8080"
    environment:
      HL7_UTILS_PORT: 8080
